# Generated by Django 4.2.6 on 2024-01-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='total',
        ),
    ]
